In [1]:
import torch, torchvision

# GPU Check
---

In [2]:
torch.cuda.is_available()

True

# Model Load

In [3]:
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [4]:
data.numpy()

array([[[[0.8335438 , 0.28140712, 0.8501863 , ..., 0.08919442,
          0.00481218, 0.6175365 ],
         [0.29640263, 0.60647655, 0.26799774, ..., 0.83481234,
          0.63907677, 0.78566027],
         [0.81549144, 0.7647918 , 0.0785616 , ..., 0.21540976,
          0.05701822, 0.5370347 ],
         ...,
         [0.61064315, 0.5421125 , 0.22154307, ..., 0.7433896 ,
          0.37267256, 0.23645967],
         [0.3393036 , 0.5362612 , 0.8353816 , ..., 0.9525679 ,
          0.0090754 , 0.25519747],
         [0.02438271, 0.36653572, 0.84238464, ..., 0.8494267 ,
          0.580447  , 0.46284384]],

        [[0.08326375, 0.15619683, 0.03041935, ..., 0.45096898,
          0.679757  , 0.82344514],
         [0.24082571, 0.52228814, 0.3576421 , ..., 0.2316019 ,
          0.3478691 , 0.33452654],
         [0.67872864, 0.1491614 , 0.71433544, ..., 0.7266917 ,
          0.21321201, 0.9840786 ],
         ...,
         [0.00767672, 0.3594693 , 0.40966266, ..., 0.75060266,
          0.09186625, 0.4

In [5]:
labels.numpy()

array([[0.70320845, 0.7584678 , 0.6260037 , 0.00609529, 0.19023633,
        0.42018825, 0.10333043, 0.41852593, 0.8902591 , 0.5757377 ,
        0.5331904 , 0.8466513 , 0.44572103, 0.8287859 , 0.46107882,
        0.0937497 , 0.09704739, 0.63301873, 0.679656  , 0.9470375 ,
        0.94760126, 0.4539081 , 0.5173742 , 0.30830556, 0.2981987 ,
        0.10729581, 0.64772695, 0.4072253 , 0.46949732, 0.66320527,
        0.35316718, 0.88099486, 0.31291693, 0.7831332 , 0.74823534,
        0.9523634 , 0.2989356 , 0.6886542 , 0.8344162 , 0.4246832 ,
        0.6118151 , 0.64438325, 0.45279104, 0.913808  , 0.6781547 ,
        0.76916903, 0.30022568, 0.82419485, 0.23227805, 0.81121886,
        0.39610893, 0.9446649 , 0.6018221 , 0.97164243, 0.35105175,
        0.8068249 , 0.21201563, 0.38717616, 0.81264937, 0.52706623,
        0.5549539 , 0.80450416, 0.51722485, 0.570475  , 0.829471  ,
        0.19182968, 0.9413175 , 0.8497549 , 0.03764051, 0.79190874,
        0.9341625 , 0.2884326 , 0.5498829 , 0.01

In [6]:
prediction = model(data)

In [7]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [8]:
loss

tensor(-500.2837, grad_fn=<SumBackward0>)

In [9]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [10]:
optim

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)

In [11]:
optim.step() #gradient descent

# Differentiation in Autograd
---

In [12]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [13]:
Q = 3*a**3 - b**2

In [14]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [15]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [16]:
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

# Computational Graph

In [17]:
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 10)
test_data = torch.rand(1, 3, 64,64)

In [18]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients? : {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

Does `a` require gradients? : False
Does `b` require gradients?: True


In [19]:
from torch import nn, optim

model = torchvision.models.resnet18(pretrained=True)

# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

In [20]:
model.fc = nn.Linear(512,10)

In [21]:
optimizer = optim.SGD(model.fc.parameters(), lr=1e-2, momentum=0.9)

In [22]:
prediction = model(data)

In [23]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [24]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [25]:
optim.step()

In [28]:
model(test_data).detach().numpy()

array([[-4.6708746, -4.2578926, -4.6880746, -4.7507253, -4.450863 ,
        -5.5752482, -4.9015846, -3.6900647, -4.780111 , -3.3442442]],
      dtype=float32)